# Generated by Django 5.1.4 on 2025-01-02 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelife', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chore',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['purchased', 'name']},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sharedcalendarevent',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AddField(
            model_name='chore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='household',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sharedcalendarevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
