# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kobrasuite-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Get dependencies
        run: |
          cd ./kobrasuite_app
          flutter pub get

      - name: Build for web
        run: |
          cd ./kobrasuite_app
          flutter build web

      - name: Prepare for deployment
        run: |
          cd ./kobrasuite_app
          mkdir wwwroot
          cp -r build/web/* wwwroot/
          cp server.js wwwroot/

      - name: Zip artifact for deployment
        run: zip release.zip ./kobrasuite_app -r -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip ./release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_81541AC136FA4B749D2C0017BE1F60CD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_649382B575D04D37A4DC4EB0A15A2793 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6E763AD720E4446EB25B89D3BFD7FDE5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kobrasuite-frontend'
          slot-name: 'Production'
          package: ./kobrasuite_app
